### PR TITLE
add check password

### PR DESCRIPTION
**Pull request by Tanson**
> The wifi password must be greater than or equal to 8

Sorry, I put the private use of the code submitted.

new request is added help Page, Web AUTH, Web config Page.How can I close it?

### CODE REVIEW

**Comment by dogmaphobic** [comment]
What is this? Why was the README basically wiped out? Why change the SSID? Baud rate?

**Comment by Tanson** [comment]
SSID just because of personal habits only, if you mind I modified back. Baud rate is because Pixhawk's default speed is 57600, the use of more convenient

**Comment by dogmaphobic** [comment]
This firmware is being used by a whole lot of people. It would be a very bad idea to change the SSID. The PixHawk default baud rate for the ESP bridge is 921600. Changing it to something else will break everything out there.

**Comment by pkocmoud** [comment]
@Tanson  This was designed for the Pixracer whose wifi telemetry port defaults to 921600, what flight controller are you attempting to connect to?

**Comment by mzahana** [comment]
I guess the highest baud is much better. Becaus it provides higher throughput .

**Comment by pkocmoud** [comment]
This has worked well with and for the Pixracer for quite some time.

**Comment by Tanson** [comment]
How can I close it

**Pull request closed without merging**
