### PR TITLE
Static IP support

### PR DESCRIPTION
**Pull request by dennisss**
- Allow setting a static IP address while in STA mode.

- Verified to work on a PixRacer

### CODE REVIEW

**Comment by mzahana** [comment]
Already merged?

**Comment by dogmaphobic** [comment]
> Already merged?

No, not yet. I won't have time to take a look at it until later today.

**Comment by samacumen** [comment]
@dogmaphobic I have been using your library (mavesp8266), thanks for the good work. Is static IP supported on the prebuilt binary firmware_v1.1.1 as given on this page (https://pixhawk.org/peripherals/8266). It hasn't worked yet. What are the steps to make it work?

Some of the commands given here (https://github.com/dogmaphobic/mavesp8266/blob/master/HTTP.md), esp. setting gateway and netmask for static IP just don't work.

Any help would be great.

**Comment by dogmaphobic** [comment]
It should be. Nothing has changed since 1.1.1. I haven't used this myself in ages. You may have better luck asking on gitter: https://gitter.im/dogmaphobic/mavesp8266

**Pull request merged**
